// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://supofkreaxrgofoqrooo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1cG9ma3JlYXhyZ29mb3Fyb29vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3Mzc4ODYsImV4cCI6MjA1MTMxMzg4Nn0.kpLuF5aR-0fKU77t4zMyZ-R6op_Yxb0bRyOyVaEnp4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);